import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { syncPlugin } from "./esbuild.config.dev.mjs"; 

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"fs",
		"node:fs",
		"node:crypto",
		"node:url",
		"node:path",
		"node:events",
		"node:stream",
		"node:string_decoder",
		"node:assert",
		"node:buffer",
		"node:util",
		"node:os",
		"node:zlib",
		"node:child_process",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: prod ? [] : [syncPlugin]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
